apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
commonLabels:
  app: dev-web
  release: dev
namespace: dev
resources:
  - ../../base
images:
  - name: crkushal7/manager
    newName: crkushal7/web
    newTag: web-main-227b610cbd3eb56f1b99d07aefc620e3de5258ea
  - name: crkushal7/web
    newName: crkushal7/web
configMapGenerator:
  - envs:
      - .env
    name: web-config
