apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
commonLabels:
  app: dev-web
  release: dev
namespace: dev
resources:
  - ../../base
images:
  - name: crkushal7/web
    newName: crkushal7/web
    newTag: web-main-dc0e33be7f33ccaf28a47267f2a5ea8da9812501
configMapGenerator:
  - envs:
      - .env
    name: web-config
