name: Core - Build

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: "./"

jobs:
  app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: "^1.13.1"

      - name: Install dependencies
        run: |
          go mod download
          go install .

      - name: Format code
        run: |
          go fmt

      - name: test
        run: |
          go test -v

      - name: Build app
        run: |
          go build auth

  build-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build docker image
        run: |
          make docker-build

      - name: Tag latest image
        run: |
          make docker-tag

      - name: Push image
        run: |
          make docker-push

      - name: Update Kustomization
        run: |
          make edit-image-name

      - name: Commit changes
        run: |
          git config --global user.name "test-bot"
          git config --global user.email "test-bot@infra.com"
          git add .
          git commit -m "${{ github.head_ref }}"

      - name: Push to branch
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.INFRA_TOKEN }}
          branch: ${{ github.base_ref || github.ref_name }}
