apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
commonLabels:
  app: dev-auth
  release: dev
namespace: dev
resources:
  - ../../base
images:
  - name: app/auth
    newName: crkushal7/app/auth
