apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: web-service
spec:
  selector:
    app: web
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
