apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
commonLabels:
  app: dev-manager
  release: dev
namespace: dev
resources:
  - ../../base
images:
  - name: app/manager
    newName: crkushal7/app/manager
configMapGenerator:
  - envs:
      - .env
    name: manager-config
