apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
commonLabels:
  app: dev-nginx
  release: dev
namespace: dev
resources:
  - ../../base
images:
  - name: crkushal7/nginx
    newName: crkushal7/nginx
    newTag: nginx-main-4c8aa06f372a2cc78bd6b4468c8cdfb5017c2034
configMapGenerator:
  - envs:
      - .env
    name: nginx-config
