apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
commonLabels:
  app: dev-nginx
  release: dev
namespace: dev
resources:
  - ../../base
images:
  - name: crkushal7/nginx
    newName: crkushal7/nginx
    newTag: nginx-main-d929f38e3f0f15a7c2d7562b6262ba23adea4ae9
configMapGenerator:
  - envs:
      - .env
    name: nginx-config
