apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
commonLabels:
  app: dev-nginx
  release: dev
namespace: dev
resources:
  - ../../base
images:
  - name: crkushal7/nginx
    newName: crkushal7/nginx
    newTag: nginx-main-74ba209cdc7ef703d4a940860a653082cb1a8c6e
configMapGenerator:
  - envs:
      - .env
    name: nginx-config
