apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-
commonLabels:
  app: dev-nginx
  release: dev
namespace: dev
resources:
  - ../../base
images:
  - name: crkushal7/nginx
    newName: crkushal7/nginx
    newTag: nginx-main-13553f2ffe77a204484756cdaac6000a0ef2b846
configMapGenerator:
  - envs:
      - .env
    name: nginx-config
