apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
commonLabels:
  app: prod-web
  release: prod
namespace: prod
resources:
  - ../../base
images:
  - name: crkushal7/web
    newName: crkushal7/web
replicas:
  - name: web
    count: 5
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      spec:
        containers:
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: dev-web-config
                  key: PORT
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: dev-web-config
                  key: HOST
            - name: ADMIN_URL
              valueFrom:
                configMapKeyRef:
                  name: dev-web-config
                  key: ADMIN_URL
            - name: MANAGER_URL
              valueFrom:
                configMapKeyRef:
                  name: dev-web-config
                  key: MANAGER_URL
            - name: NGINX_URL
              valueFrom:
                configMapKeyRef:
                  name: dev-web-config
                  key: NGINX_URL
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: not-used
      spec:
        template:
          spec:
            containers:
              - name: nginx
                image: nginx:1.21.0
    target:
      labelSelector: "app.kubernetes.io/name=nginx"
