name: Nginx Build

on:
  pull_request:
    types: [synchronize, closed, opened]
    branches:
      - dev

defaults:
  run:
    working-directory: "./apps/nginx/"

jobs:
  build-image:
    runs-on: ubuntu-latest
    if: "(contains(github.base_ref, 'dev') && github.event.pull_request.merged)"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Detect changes in "src/**" directory
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            src:
              - 'apps/nginx/k8s/**'

      - name: Login to Docker Hub
        if: steps.changes.outputs.src == 'false'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build docker image
        if: steps.changes.outputs.src == 'false'
        run: |
          make docker-build

      - name: Tag latest image
        if: steps.changes.outputs.src == 'false'
        run: |
          make docker-tag

      - name: Push image
        if: steps.changes.outputs.src == 'false'
        run: |
          make docker-push

      - name: Update Kustomization
        if: steps.changes.outputs.src == 'false'
        run: |
          make edit-image-name

      - name: Commit changes
        if: steps.changes.outputs.src == 'false'
        run: |
          git config --global user.name "test-bot"
          git config --global user.email "test-bot@infra.com"
          git add .
          git commit -m "Updated Kustomization file"

      - name: Push to branch
        if: steps.changes.outputs.src == 'false'
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.INFRA_TOKEN }}
          branch: ${{ github.base_ref || github.ref_name }}
